<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cashcourse"
 *
 * Auto generated by Extension Builder 2018-05-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Bootstrap 4.1',
    'description' => 'Bootstrap 4.1',
    'category' => 'plugin',
    'author' => 'Vitali Scharov',
    'author_email' => 'scharov@knowex.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];